import type {
  CommentData,
  NotificationData,
  PostData,
  ProfileData,
} from "@/showcase/types";

export const currentProfile: ProfileData = {
  name: "Campbell",
  handle: "@campbell",
  initials: "CB",
  bio: "Building small things for good people. Usually outside by sunset.",
  joined: "Joined July 2026",
  posts: 48,
  friends: 42,
};

export const posts: PostData[] = [
  {
    id: "porch-frog",
    identity: "Mossy Moose",
    avatar: "🫎",
    time: "2m",
    body: "okay who left the tiny ceramic frog on my porch? he has been promoted to head of security.",
    comments: 14,
    score: 86,
    unread: true,
  },
  {
    id: "reservoir-walk",
    identity: "Campbell",
    avatar: "CB",
    handle: "@campbell",
    time: "18m",
    body: "Sunset walk at the reservoir tonight. Leaving around 7 if anyone wants to join.",
    comments: 6,
    score: 31,
    image: true,
    mine: true,
  },
  {
    id: "breakfast",
    identity: "Electric Otter",
    avatar: "🦦",
    time: "43m",
    body: "Hot take: breakfast food tastes better after 10pm. I will not be taking questions at this time.",
    comments: 22,
    score: 104,
    unread: true,
  },
  {
    id: "ladder",
    identity: "Soft Fox",
    avatar: "🦊",
    time: "1h",
    body: "Does anybody have a ladder I can borrow for literally fifteen minutes? There is a frisbee situation.",
    comments: 9,
    score: 27,
    unread: true,
  },
  {
    id: "playlist",
    identity: "Campbell",
    avatar: "CB",
    handle: "@campbell",
    time: "3h",
    body: "Made a six-hour playlist for a forty-minute drive. This is normal and measured behavior.",
    comments: 4,
    score: 19,
    mine: true,
  },
];

export const comments: CommentData[] = [
  {
    id: "comment-1",
    identity: "Quiet Badger",
    avatar: "🦡",
    time: "12m",
    body: "I’m in. Are we meeting at the north lot again?",
    score: 12,
    replies: 2,
    depth: 0,
  },
  {
    id: "comment-2",
    parentId: "comment-1",
    identity: "Campbell",
    avatar: "CB",
    handle: "@campbell",
    time: "10m",
    body: "Yep—north lot by the trail map. I’ll bring extra water.",
    score: 8,
    replies: 1,
    depth: 1,
    postAuthor: true,
  },
  {
    id: "comment-3",
    parentId: "comment-2",
    identity: "Golden Moth",
    avatar: "🦋",
    time: "7m",
    body: "Can I claim one of those waters? I’m coming straight from work.",
    score: 5,
    replies: 0,
    depth: 2,
  },
  {
    id: "comment-4",
    identity: null,
    time: "6m",
    body: null,
    score: 0,
    replies: 1,
    depth: 0,
  },
  {
    id: "comment-5",
    parentId: "comment-4",
    identity: "Mossy Moose",
    avatar: "🫎",
    time: "4m",
    body: "I’ll be there around 7:10. Don’t wait on me if you’re ready.",
    score: 7,
    replies: 0,
    depth: 1,
  },
];

export const notifications: NotificationData[] = [
  {
    id: "notification-1",
    kind: "reply",
    avatar: "🦡",
    actor: "Quiet Badger",
    text: "replied to your post",
    excerpt: "Are we meeting at the north lot again?",
    time: "12m",
    unread: true,
  },
  {
    id: "notification-2",
    kind: "vote",
    avatar: "♥",
    actor: "8 friends",
    text: "upvoted your reservoir post",
    time: "24m",
    unread: true,
  },
  {
    id: "notification-3",
    kind: "mention",
    avatar: "🦊",
    actor: "Soft Fox",
    text: "mentioned you in a reply",
    excerpt: "@campbell do you still have that tiny step ladder?",
    time: "1h",
    unread: false,
  },
  {
    id: "notification-4",
    kind: "system",
    avatar: "W",
    actor: "WakYak",
    text: "Your porch post was reviewed and is all good.",
    time: "Yesterday",
    unread: false,
  },
  {
    id: "notification-5",
    kind: "mention",
    avatar: "🦦",
    actor: "Electric Otter",
    text: "mentioned you in a post",
    excerpt: "This breakfast take is for @campbell specifically.",
    time: "Yesterday",
    unread: false,
  },
];

export const trends = [
  { eyebrow: "Tonight", title: "Reservoir walk", detail: "12 posts" },
  { eyebrow: "Popular", title: "The porch frog", detail: "86 points" },
  { eyebrow: "Food", title: "Late night breakfast", detail: "24 posts" },
];
